service: project3-aws-telegram

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  profile: auto-curso
  region: us-east-1
  stage: prod
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - ce:GetCostAndUsage
          Resource: "*"

functions:
  get_cost:
    handler: handler.get_cost
    events:
      - schedule: 
          rate: rate(1 minute)
          enabled: true
          input: {}
      - schedule: 
          rate: cron(0 23 * * ? *)
          enabled: true
          input: {}

plugins:
  - serverless-python-requirements
package:
  patterns:
    - "!.venv"
    - "!node_modules"
    - "!*.json"
